coverage:
  status:
    project:
      default:
        target: 100%
        paths: 
          - "src"
          - "index.js"
    patch:
      default:
        target: 100%
        paths: 
          - "src"
          - "index.js"